name: CI/CD - Innovatech Chile

on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 815427406831.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    name: Build y publicar imágenes en ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login a Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y push Frontend
        run: |
          docker build -t $ECR_REGISTRY/innovatech-frontend:latest ./front_despacho
          docker push $ECR_REGISTRY/innovatech-frontend:latest

      - name: Build y push Backend Despachos
        run: |
          docker build -t $ECR_REGISTRY/innovatech-back-despachos:latest ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          docker push $ECR_REGISTRY/innovatech-back-despachos:latest

  deploy:
    name: Deploy en ECS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Redeploy Frontend en ECS
        run: |
          aws ecs update-service \
            --cluster innovatech-cluster \
            --service innovatech-frontend-service \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Redeploy Backend en ECS
        run: |
          aws ecs update-service \
            --cluster innovatech-cluster \
            --service innovatech-backend-service \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Esperar estabilización Frontend
        run: |
          aws ecs wait services-stable \
            --cluster innovatech-cluster \
            --services innovatech-frontend-service \
            --region $AWS_REGION

      - name: Esperar estabilización Backend
        run: |
          aws ecs wait services-stable \
            --cluster innovatech-cluster \
            --services innovatech-backend-service \
            --region $AWS_REGION
